# --- 게임 규칙 상수 ---
PLAYERS_PER_TEAM = 5
TEAMS_PER_MATCH = 2
PLAYERS_PER_MATCH = PLAYERS_PER_TEAM * TEAMS_PER_MATCH  # 10

# --- 팀 구성 규칙 상수 ---
REQUIRED_TANKS_PER_TEAM = 1
REQUIRED_HEALERS_PER_TEAM = 1

# 자유 역할군(FLEX)의 수는 전체 팀원에서 필수 역할군 수를 빼서 계산
FLEX_ROLES_PER_TEAM = PLAYERS_PER_TEAM - (REQUIRED_TANKS_PER_TEAM + REQUIRED_HEALERS_PER_TEAM) # 3